name: signac-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - signac
  - signac-flow
  - ffmpeg
  - cloudpickle
  - htop
  - pandas
  - pip:
    - sacred
    - datreant
